In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#@title Initialisations
batch_size = 8
teacher_epsilons = [0.1, 0.1]   # len = num_teachers
num_observations = 2

learn_teacher_epsilons = [0, 1]     # bool 
learned_teacher_epsilons = [0.2]    # len = sum(learn_teacher_epsilons)

bounds = 0.2       # set threshold on distance to target

In [3]:
#@title Create and update the tf teacher epsilons

teacher_epsilons = tf.repeat(tf.convert_to_tensor([teacher_epsilons]),
                                repeats=batch_size,
                                axis=0)
learned_teacher_epsilons = tf.repeat(tf.convert_to_tensor([learned_teacher_epsilons]),
                                   repeats=batch_size,
                                   axis=0)
teacher_epsilons = tf.Variable(teacher_epsilons)
learned_teacher_epsilons = tf.Variable(learned_teacher_epsilons)

# Check for dimension mismatch
tf.debugging.assert_equal(tf.shape(learned_teacher_epsilons)[1], sum(learn_teacher_epsilons))

In [4]:
count = 0
for i, x in enumerate(learn_teacher_epsilons):
    print(i)
    if x:
        teacher_epsilons = teacher_epsilons[:, i].assign(learned_teacher_epsilons[:, count])
        count += 1

0
1


In [5]:
print(teacher_epsilons)

<tf.Variable 'UnreadVariable' shape=(8, 2) dtype=float32, numpy=
array([[0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2]], dtype=float32)>


In [6]:
obs = tf.convert_to_tensor(np.random.randn(batch_size, 2))
obs_bool = tf.cast(tf.where(abs(obs) <= bounds, 0, 1), dtype=tf.float32)
teacher_epsilons.assign(obs_bool * teacher_epsilons)

<tf.Variable 'UnreadVariable' shape=(8, 2) dtype=float32, numpy=
array([[0.1, 0. ],
       [0.1, 0. ],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2],
       [0.1, 0.2]], dtype=float32)>

In [7]:
print(obs)

tf.Tensor(
[[ 0.66005585  0.01769668]
 [ 0.50409463  0.06478766]
 [ 1.47322269  1.37718576]
 [ 0.40931899 -0.30888463]
 [-1.59646473 -1.85941275]
 [ 0.55760037 -0.23526189]
 [-1.34385533  0.28272881]
 [ 0.6810356   1.53088224]], shape=(8, 2), dtype=float64)
